package com.example.pokemax

private val moveTranslations = mapOf(
    "thunder shock" to "Choque do Trovão",
    "pin missile" to "Míssil de Espinhos",
    "thunderbolt" to "Relâmpago",
    "thunder wave" to "Onda de Choque",
    "thunder" to "Trovão",
    "tackle" to "Investida",
    "quick attack" to "Ataque Rápido",
    "flamethrower" to "Lança-Chamas",
    "water gun" to "Jato de Água",
    "scratch" to "Arranhão",
    "ember" to "Brasa",
    "vine whip" to "Chicote de Vinha",
    "hyper beam" to "Hiper Raio",
    "solar beam" to "Raio Solar",
    "earthquake" to "Terremoto",
    "shadow ball" to "Bola Sombria",
    "iron tail" to "Cauda de Ferro",
    "surf" to "Surf",
    "fly" to "Voar",
    "dig" to "Cavar",
    "psychic" to "Psíquico",
    "bite" to "Mordida",
    "slash" to "Garra",
    "body slam" to "Pancada",
    "hydro pump" to "Hidro Bomba",
    "fire blast" to "Explosão de Fogo",
    "blizzard" to "Nevasca",
    "agility" to "Agilidade",
    "double team" to "Multiplicação",
    "rest" to "Descanso",
    "substitute" to "Substituto",
    "protect" to "Proteção",
    "toxic" to "Tóxico",
    "reflect" to "Refletir",
    "light screen" to "Tela de Luz",
    "dragon claw" to "Garra de Dragão",
    "aurora beam" to "Raio Aurora",
    "ice beam" to "Raio Congelante",
    "fire spin" to "Chama Giratória",
    "swift" to "Velocidade",
    "headbutt" to "Cabeçada",
    "sing" to "Canção de Ninar",
    "sleep powder" to "Pó do Sono",
    "stun spore" to "Pó Paralisante",
    "poison powder" to "Pó Venenoso",
    "hypnosis" to "Hipnose",
    "confuse ray" to "Raio Confuso",
    "will o wisp" to "Fogo Fátuo",
    "shadow claw" to "Garra Sombria",
    "dark pulse" to "Pulso Sombrio",
    "focus blast" to "Explosão de Foco",
    "energy ball" to "Esfera de Energia",
    "scald" to "Água Fervente",
    "giga drain" to "Giga Dreno",
    "leech seed" to "Semente Sanguessuga",
    "swords dance" to "Dança das Espadas",
    "dragon dance" to "Dança do Dragão",
    "nasty plot" to "Maquinação",
    "calm mind" to "Paz de Espírito",
    "bulk up" to "Fortalecer",
    "roost" to "Poleiro",
    "recover" to "Recuperação",
    "synthesis" to "Síntese",
    "moonlight" to "Luz do Luar",
    "morning sun" to "Sol da Manhã"
)

fun translateMoveName(moveName: String?): String {
    if (moveName.isNullOrBlank()) return ""
    val clean = moveName.lowercase().replace('-', ' ').trim()
    return moveTranslations[clean] ?: clean.split(' ').joinToString(" ") { word ->
        word.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
    }
}
